name: desafio_guia_motel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  infinite_scroll_pagination: ^4.0.0
  dio: ^5.5.0+1
  get: ^4.6.6
  intl: ^0.18.1
  test: ^1.6.1
  mockito: ^5.4.2
  build_runner: ^2.4.6
  provider: ^6.1.2


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
